// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1GqJrqGFf1JI1iMT-c1Deyxd7eYIaZK4',
    appId: '1:573873722774:web:2fd13ed0da711309b079b7',
    messagingSenderId: '573873722774',
    projectId: 'analytic-test-111e1',
    authDomain: 'analytic-test-111e1.firebaseapp.com',
    storageBucket: 'analytic-test-111e1.appspot.com',
    measurementId: 'G-6L4PDFHZHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPUhckIxSGqe1xJbPIb0vYti9UNpooSZ8',
    appId: '1:573873722774:android:cd1f0eb21d68b8c3b079b7',
    messagingSenderId: '573873722774',
    projectId: 'analytic-test-111e1',
    storageBucket: 'analytic-test-111e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZxj9y_Q2fv36GedwyqzxNEbWCdd056yM',
    appId: '1:573873722774:ios:1f968a6c7922e215b079b7',
    messagingSenderId: '573873722774',
    projectId: 'analytic-test-111e1',
    storageBucket: 'analytic-test-111e1.appspot.com',
    iosClientId: '573873722774-98uckahcspqlfeojf7b79i7s2m9crt9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.analyticsTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZxj9y_Q2fv36GedwyqzxNEbWCdd056yM',
    appId: '1:573873722774:ios:1f968a6c7922e215b079b7',
    messagingSenderId: '573873722774',
    projectId: 'analytic-test-111e1',
    storageBucket: 'analytic-test-111e1.appspot.com',
    iosClientId: '573873722774-98uckahcspqlfeojf7b79i7s2m9crt9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.analyticsTest',
  );
}
